### ISSUE TITLE
Cannot encode ticket: AttributeError: 'GeneralizedTime' object has no attribute 'encode'

### ISSUE THREAD

**Issue by raandree** [nidem/kerberoast#11]
I am getting the following error when running this command on this ticket:

[2-40a10000-Install@http~kerbtest.a.vm.net-A.VM.NET.kirbi.txt](https://github.com/nidem/kerberoast/files/2204637/2-40a10000-Install.http.kerbtest.a.vm.net-A.VM.NET.kirbi.txt)

```
python C:\kerberoast-master\kerberoast-master\kerberoast.py -p Password1 -r $fileName -w http.kirbi -u 500
```

```
PS C:\> python C:\kerberoast-master\kerberoast-master\kerberoast.py -p Password1 -r $fileName -w http.kirbi -u 500
NO MATCH!! UPN DNS Info
NOT SAME
2000100010003000010000000000000049006e007300740061006c006c00400061002e0076006d002e006e006500740041002e0056004d002e004e0045005400

2000100010003400010000000000000049006e007300740061006c006c00400061002e0076006d002e006e00650074000000000041002e0056004d002e004e00
----
python : Traceback (most recent call last):
At line:1 char:1
+ python C:\kerberoast-master\kerberoast-master\kerberoast.py -p Passwo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "C:\kerberoast-master\kerberoast-master\kerberoast.py", line 243, in <module>
    newticket = updatepac(key, fullraw, pac)
  File "C:\kerberoast-master\kerberoast-master\kerberoast.py", line 161, in updatepac
    newencserverticket = kerberos.encrypt(key, 2, encoder.encode(decserverticket), nonce)
  File "C:\Python27\lib\site-packages\pyasn1\codec\ber\encoder.py", line 663, in __call__
    substrate = concreteEncoder.encode(value, asn1Spec, self, **options)
  File "C:\Python27\lib\site-packages\pyasn1\codec\ber\encoder.py", line 85, in encode
    value, asn1Spec, encodeFun, **options
  File "C:\Python27\lib\site-packages\pyasn1\codec\ber\encoder.py", line 450, in encodeValue
    chunk = encodeFun(component, asn1Spec, **options)
  File "C:\Python27\lib\site-packages\pyasn1\codec\ber\encoder.py", line 663, in __call__
    substrate = concreteEncoder.encode(value, asn1Spec, self, **options)
  File "C:\Python27\lib\site-packages\pyasn1\codec\ber\encoder.py", line 85, in encode
    value, asn1Spec, encodeFun, **options
  File "C:\Python27\lib\site-packages\pyasn1\codec\ber\encoder.py", line 185, in encodeValue
    substrate = value.asOctets()
  File "C:\Python27\lib\site-packages\pyasn1\type\char.py", line 84, in asOctets
    return str(self)
  File "C:\Python27\lib\site-packages\pyasn1\type\char.py", line 55, in __str__
    return self._value.encode(self.encoding)
AttributeError: 'GeneralizedTime' object has no attribute 'encode'
```

**Comment by nidem** [comment]
Odd. I can't recreate, but I know one other person had the same issue.

**Comment by raandree** [comment]
I have attached the ticket to repro this issue. Can you decrypt the ticket referenced above?

**Comment by stephenvw** [comment]
I have the same problem.
Maybe an issue with the encoding.

I try to look into it tomorrow. See if I can find a lead to the problem.

**Comment by stephenvw** [comment]
The problem already appears on cracking the kirbi file:

python tgsrepcrack.py 1.1million word list.txt MSSQLSVC.kirbi

Process Process-1:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\temp\kerberoast-master\tgsrepcrack.py", line 16, in loadwordlist
    wordlistqueue.put(w.decode('utf-8').strip(), True)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 6: invalid start byte
found password for ticket 0: PASSWD  File: MSSQLSVC.kirbi
All tickets cracked!

**Comment by nidem** [comment]
Don't crack with this tool. It is WAY too slow. Both Hashcat and John the Ripper support cracking these tickets.

**Comment by nidem** [comment]
I'm going to close this. The cracker here is severely deprecated since JtR and Hashcat do a much faster and better job.
