### ISSUE TITLE
tgsrepcrack.py error(s)

### ISSUE THREAD

**Issue by sxplitfirex** [nidem/kerberoast#16]
Hello,

I am getting this error:

```
root@kali:~/Desktop/CTF# ./tgsrepcrack.py wordlist.txt tgs.kirbi 
Traceback (most recent call last):
  File "./tgsrepcrack.py", line 71, in <module>
    for f in glob.glob(path):
  File "/usr/lib/python3.8/glob.py", line 21, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib/python3.8/glob.py", line 42, in _iglob
    dirname, basename = os.path.split(pathname)
  File "/usr/lib/python3.8/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

If I leave it running for a little longer before interrupting with Ctrl+C the error looks like this:
```
root@kali:~/Desktop/CTF# ./tgsrepcrack.py wordlist.txt tgs.kirbi 
Traceback (most recent call last):
  File "./tgsrepcrack.py", line 71, in <module>
    for f in glob.glob(path):
  File "/usr/lib/python3.8/glob.py", line 21, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib/python3.8/glob.py", line 42, in _iglob
    dirname, basename = os.path.split(pathname)
  File "/usr/lib/python3.8/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./tgsrepcrack.py", line 16, in loadwordlist
    wordlistqueue.put(w.decode('utf-8').strip(), True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 5: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 337, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 201, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by Whale3070** [comment]
the same issue
```
python3 tgsrepcrack.py -t 10 rockyou.txt tgs.kirbi 
Traceback (most recent call last):
  File "tgsrepcrack.py", line 71, in <module>
    for f in glob.glob(path):
  File "/usr/lib/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib/python3.6/glob.py", line 40, in _iglob
    dirname, basename = os.path.split(pathname)
  File "/usr/lib/python3.6/posixpath.py", line 107, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper

```

**Comment by itzBawantha** [comment]
any update

**Comment by joshuaspy** [comment]
Any update?

**Comment by Augustin-FL** [comment]
This happens when your dictionary has strange characters. For instance, entries with "ñ" are triggering this issue
