### ISSUE TITLE
Receiving the following when starting tgsrepcrack

### ISSUE THREAD

**Issue by mubix** [nidem/kerberoast#4]
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "tgsrepcrack.py", line 16, in loadwordlist
    wordlistqueue.put(w.decode('utf-8').strip(), True)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x93 in position 1: invalid start byte
```

Does this mean that the ticket is bad?

**Comment by nidem** [comment]
Sounds like it. Can you possibly share the packets and I'll look?

--Tim Medin

**Comment by mubix** [comment]
Found out what the deal was, it was my dictionary. Should dictionaries be in UTF-8?

**Comment by nidem** [comment]
It shouldn't matter. The code converts it to UTF-8. Looks like it can't
code your string via utf8. Odd.

--Tim Medin
