### ISSUE TITLE
'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by rasta-mouse** [nidem/kerberoast#8]
```
root@kali:~/kerberoast# python kerberoast.py -v -r /root/xxx.kirbi -w /root/xxx2.kirbi -p xxx
NO MATCH!! Login Info
NOT SAME
0110[...snip...]0005

0110[...snip...]0000
----
Traceback (most recent call last):
  File "kerberoast.py", line 242, in <module>
    pac = pacobj.encode()
  File "/root/kerberoast/PAC.py", line 529, in encode
    pse = ps.encode()
AttributeError: 'NoneType' object has no attribute 'encode'
```

```
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2016.1"
VERSION_ID="2016.1"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.kali.org/"
SUPPORT_URL="http://forums.kali.org/"
BUG_REPORT_URL="http://bugs.kali.org/"

Python 2.7.12
```

**Comment by nidem** [comment]
I've seen that before but I have node idea what causes it. The ticket isn't the structure I expect. Unfortunately, no one has ever send me the tickets so I can RE it and figure out what's wrong.

Can you share your ticket?

**Comment by rasta-mouse** [comment]
Hey @nidem. It was a while back, so let me see if the SPN is still about.  I could share the ticket, but can we do it over PGP?

**Comment by nidem** [comment]
Sure. My github account is tied to my key.

https://gist.github.com/nidem/8b6ffc91dd2a219d6291

**Comment by rasta-mouse** [comment]
I think your keys have expired?

```
rasta@keybase:~$ keybase pgp encrypt -m "test" timmedin
ERROR openpgp: invalid argument: cannot encrypt a message to key id bd8d902bbdecaca4 because it has no encryption keys
```
![timmedin](https://cloud.githubusercontent.com/assets/7346521/21069230/d35a3fc2-be6f-11e6-8b98-521945541b84.PNG)

**Comment by nidem** [comment]
I just updated it

**Comment by nidem** [comment]
Old
