### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by phvin** [nidem/kerberoast#9]
I'm getting the following error when trying to crack the kirbi file:

```
root@kali:~/kerberoast$ python tgsrepcrack.py 1-xxx.COM.kirbi /pentest/dictionaries/bigpicch.txt
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "tgsrepcrack.py", line 16, in loadwordlist
    wordlistqueue.put(w.decode('utf-8').strip(), True)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x82 in position 1: invalid start byte
All tickets cracked!
```

**Comment by nidem** [comment]
Don't use this tool. It is going to be much much faster with Hashcat or John the Ripper.
